// <auto-generated />
namespace Astrodon.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DisableChecks : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DisableChecks));
        
        string IMigrationMetadata.Id
        {
            get { return "201905060550260_DisableChecks"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
